aws_region                  = "us-east-1"
instance_type               = "t2.large"
subnet_id                   = "subnet-0d2642da77bbfe744"
security_group_id           = "sg-0d9f83e6b570f7720"
key_name                    = "rpxec2pair"
vol_size                    = "80"
vol_type                    = "gp3"
iam_instance_profile_name   = "dev-ia-instance-profile-role"
