variable "aws_region" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "security_group_id" {}
variable "key_name" {}
variable "availability_zone" {}
variable "vol_size" {}
variable "vol_type" {}
variable "iam_instance_profile_name" {}
