---
- name: Deploy Ruby on Rails app using RVM and Capistrano
  hosts: rails-app
  become: yes
  vars:
    ruby_version: "3.0.0"
    app_user: ubuntu
    deploy_branch: "{{ branch | default('main') }}"

  tasks:
    - name: Ensure RVM is installed (basic check)
      stat:
        path: /home/{{ app_user }}/.rvm/scripts/rvm
      register: rvm_check

    - name: Fail if RVM is not installed
      fail:
        msg: "RVM not found at /home/{{ app_user }}/.rvm/scripts/rvm. Please install RVM."
      when: not rvm_check.stat.exists

    - name: Use Ruby version via RVM
      shell: |
        source /home/{{ app_user }}/.rvm/scripts/rvm
        rvm use {{ ruby_version }} --default
      args:
        executable: /bin/bash

    - name: Install bundler and run bundle install
      shell: |
        source /home/{{ app_user }}/.rvm/scripts/rvm
        rvm use {{ ruby_version }} --default
        gem install bundler:2.5.1
        bundle install
      args:
        chdir: /path/to/your/app  # update to your app directory on remote
        executable: /bin/bash

    - name: Run Capistrano deploy
      shell: |
        source /home/{{ app_user }}/.rvm/scripts/rvm
        rvm use {{ ruby_version }} --default
        cap qa deploy BRANCH={{ deploy_branch }} USERNAME={{ app_user }}
      args:
        chdir: /path/to/your/app  # update to your app directory on remote
        executable: /bin/bash
